version: '3'

services:
  nginx:
    image: moritzschramm/nginx-laravel:1.0
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    networks:
      - appnet
  php:
    image: moritzschramm/php-laravel:1.0
    volumes:
      - .:/var/www/html
    networks:
      - appnet

networks:
  appnet:
    driver: "bridge"

volumes:
  data:
    driver: "local"
